<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNrndojw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNrndojw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNrndojw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNrndojw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNrndojw\appProdProjectContainer([
    'container.build_hash' => 'Nrndojw',
    'container.build_id' => '2384fed6',
    'container.build_time' => 1579682223,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNrndojw');
